version: '3'
services:
  db:
    image: "cassandra" 
    ports:
    - "7199:7199"
    - "7000:7000"
    - "9042:9042"
    - "9160:9160"
    - "7001:7001"
    networks: 
      yo:
  node:
    image: "node:8"
    command: bash -c "cd /var/www && npm install && npm start"
    volumes:
      - .:/var/www/
    ports:
      - "3001:3001"
    networks:
      yo:
  # node2:
  #   image: "node:7"
  #   command: bash -c "ping node"
  #   ports:
  #     - "3002:3002"
  #   networks:
  #     yo:

networks:
  yo:
    driver: bridge

    
